
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className="flex flex-col gap-10 bg-gradient-to-b from-gray-900 to-gray-600 items-center py-10 ">
      <h1 className='text-white text-2xl font-bold w-fit '>SignUp</h1>
      {children}
      </body>
    </html>
  );
}
